--- #YAML:1.0
name:                PITA-Test-Dummy-Perl5-Make
version:             1.04
abstract:            CPAN Test Dummy for PITA Makefile.PL installs
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam Kennedy <cpan@ali.as>
